counterapp/urls.py
from django.urls import path

from . import views

app_name = 'counterapp'

urlpatterns = [
    path('predict/<int:video_id>', views.predict, name='predict'),
]

growlivapp/urls.py
from django.urls import path

from . import views
from .views import BusinessLoginView, BusinessRegisterView

app_name = 'growlivapp'

urlpatterns = [
    # path for the home page
    path('', views.home, name='home'),

    # path for the login and registration pages
    path('login/', BusinessLoginView.as_view(), name='login'),
    path('signup/', BusinessRegisterView.as_view(), name='signup'),

    path('upload/', views.upload_video, name='upload'),
    path('profile/', views.profile, name='profile'),
    path('scan_detail/', views.scan_detail_page, name='scan_detail_page'),

    # path for login related pages
    path('instruction/', views.instructions, name='instruction'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('change_password/', views.change_password, name='change_password'),
    path('logout/', views.logout_user, name='logout_user'),
    path('change_password/', views.change_password, name='change_password'),
    path('delete_record/<int:record_id>/', views.delete_record, name='delete_record'),

]

mitecountpro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mitecountpro import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('growlivapp.urls')),
    path('count/', include('counterapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

growlivapp/models.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Business(User):
    business_name = models.CharField(max_length=50)
    business_phone = PhoneNumberField()
    contact_person_name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Businesses"


class Video(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, null=True, default=None)
    video = models.FileField(upload_to='mite_videos', validators=[FileExtensionValidator(
        allowed_extensions=['asf', 'avi', 'gif', 'm4v', 'mkv', 'mov', 'mp4', 'mpeg', 'mpg', 'ts', 'wmv', 'webm'])])
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.video.name

GrowLivApp/forms.py
# GrowLivApp/forms.py
from django import forms
from .models import Photo

# GrowLivApp/forms.py
from django import forms
from .models import Photo

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class PhotoForm(forms.ModelForm):
    photo = MultipleFileField(label='Select files', required=False)

    class Meta:
        model = Photo
        fields = ['photo', ]

class SignUpForm(forms.Form):
    username = forms.CharField(max_length=30)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)

growlivapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Video, Business


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['video']


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label='Email')

    class Meta:
        model = Business
        fields = ['email']


class BusinessForm(UserCreationForm):
    email = forms.EmailField(label='Email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'un', 'placeholder': field.label})

    class Meta:
        model = Business
        fields = ['email', 'password1', 'password2', 'business_name', 'business_phone', 'contact_person_name']

GrowLivApp/views.py
# GrowLivApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password, check_password
from .models import CustomUser, Business
from .forms import SignUpForm, LoginForm

# GrowLivApp/views.py
from django.shortcuts import render, redirect
# GrowLivApp/views.py
from django.contrib.auth.hashers import make_password
from .models import Photo
from django.shortcuts import render, redirect
from .forms import PhotoForm

def upload_photos(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_images = form.cleaned_data['photo']
            for image in uploaded_images:
                user = CustomUser.objects.filter(username=request.user)
                Photo.objects.create(user=user[0], image=image)
            return redirect('GrowLivApp:home')  # Redirect to your home or another page after successful upload
    else:
        form = PhotoForm()

    return render(request, 'GrowLivApp/upload_photos.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = CustomUser(username=username, email=email, password=make_password(password))
            user.save()

            # Redirect to login or home page
            return redirect('GrowLivApp:login')
    else:
        form = SignUpForm()

    return render(request, 'GrowLivApp/signup.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            try:
                user = CustomUser.objects.get(username=username)
                if check_password(password, user.password):
                    # Set session variables
                    request.session['user_id'] = user.id
                    request.session['username'] = user.username

                    return redirect('GrowLivApp:home')
                else:
                    # Incorrect password
                    return render(request, 'GrowLivApp/login.html', {'form': form, 'error': 'Invalid credentials'})
            except CustomUser.DoesNotExist:
                # User does not exist
                return render(request, 'GrowLivApp/login.html', {'form': form, 'error': 'Invalid credentials'})
    else:
        form = LoginForm()

    return render(request, 'GrowLivApp/login.html', {'form': form})

def home(request):
    # Retrieve user information from session
    user_id = request.session.get('user_id')
    username = request.session.get('username')

    return render(request, 'GrowLivApp/home.html', {'username': username})

growlivapp/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from counterapp.models import Result
from .forms import VideoForm, BusinessForm, ForgotPasswordForm
from .models import Business


def scan_detail_page(request):
    # Fetch all scan results or use filters as needed
    scan_results = Result.objects.filter(video__business__email=request.user.email).order_by('-scan_date')

    # Pass the results to the template
    context = {
        'scan_results': scan_results,
    }
    return render(request, template_name='growlivapp/scan_details.html', context=context)


def upload_video(request):
    if request.method == 'POST':
        form = VideoForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            business = Business.objects.get(username=request.user)
            video = form.save(commit=False)
            video.business = business
            video.save()
            return redirect('counterapp:predict', video_id=video.id)

    else:
        form = VideoForm()

    return render(request, template_name='growlivapp/home.html', context={'form': form})


class BusinessRegisterView(CreateView):
    template_name = 'growlivapp/signup.html'
    form_class = BusinessForm
    success_url = reverse_lazy('growlivapp:login')

    def get(self, request, *args, **kwargs) -> HttpResponse:
        if request.user.is_authenticated:
            return HttpResponseRedirect(redirect_to=reverse(viewname='growlivapp:home'))
        return super().get(request=request, *args, **kwargs)

    def post(self, request, *args, **kwargs) -> HttpResponse:
        form = BusinessForm(request.POST)
        if form.is_valid():
            business = form.save(commit=False)
            business.username = form.cleaned_data.get('email')
            form.save()
            return HttpResponseRedirect(redirect_to=reverse(viewname='growlivapp:login'))
        return render(request, template_name='growlivapp/signup.html', context={'form': form})


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = ''
        self.fields['username'].widget.attrs.update({
            'class': 'un',
            'placeholder': 'Email'
        })
        self.fields['password'].label = ''
        self.fields['password'].widget.attrs.update({
            'class': 'un',
            'placeholder': 'Password'
        })


class BusinessLoginView(LoginView):
    template_name = 'growlivapp/login.html'
    form_class = CustomAuthenticationForm

    def post(self, request, *args, **kwargs) -> HttpResponseRedirect | HttpResponse:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request=request, username=username, password=password)
        if user:
            if check_password(password, user.password):
                request.session['user_id'] = user.id
                request.session['username'] = user.username
                login(request=request, user=user)
                return HttpResponseRedirect(redirect_to=reverse(viewname='growlivapp:home'))
            else:
                return render(request, template_name='growlivapp/login.html',
                              context={'err': 'Login details are incorrect. Please try again.',
                                       'form': CustomAuthenticationForm(request.POST)})
        else:
            return render(request, template_name='growlivapp/login.html',
                          context={'err': 'Login details are incorrect. Please try again.',
                                   'form': CustomAuthenticationForm(request.POST)})

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect | HttpResponse:
        if request.user.is_authenticated:
            return HttpResponseRedirect(redirect_to=reverse(viewname='growlivapp:home'))
        return super().get(request=request, *args, **kwargs)


def instructions(request):
    return render(request, template_name='growlivapp/instruction.html')


def profile(request):
    business = Business.objects.get(email=request.user.email)
    if request.method == 'POST':
        form = BusinessForm(request.POST, instance=business)
        business.email = form.data.get('email')
        business.username = form.data.get('email')
        business.business_name = form.data.get('business_name')
        business.business_phone = form.data.get('business_phone')
        business.contact_person_name = form.data.get('contact_person_name')
        business.save()
        return redirect('growlivapp:profile')
    else:
        form = BusinessForm(instance=business)
    return render(request, template_name='growlivapp/profile.html', context={'business': form})


def forgot_password(request):
    forget_pswd_form = ForgotPasswordForm()
    if request.method == 'POST':
        email = request.POST['email']
        try:
            user = User.objects.get(email=email)
            return render(request, template_name='growlivapp/instruction.html')
        except User.DoesNotExist:
            return render(request, template_name='growlivapp/forgot_password.html',
                          context={'err': 'The email you entered does not exist in our records.',
                                   'form': forget_pswd_form})
    return render(request, template_name='growlivapp/forgot_password.html', context={'form': forget_pswd_form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('growlivapp:profile')
        else:
            # If form is not valid, add a generic message or specific error messages
            messages.error(request, 'Please correct the errors below.')
            # Optionally, add specific form error messages
            for field in form.errors:
                for error in form.errors[field]:
                    messages.error(request, f"{field}: {error}")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'growlivapp/changepassword.html', {'form': form})


@login_required
def home(request):
    # Retrieve user information from session
    user_id = request.session.get('user_id')
    username = request.session.get('username')

    return render(request, template_name='growlivapp/home.html', context={'username': username})


@login_required
def logout_user(request) -> HttpResponseRedirect:
    logout(request=request)
    return HttpResponseRedirect(redirect_to=reverse(viewname='growlivapp:login'))


def delete_record(request, record_id: int) -> HttpResponseRedirect:
    video = Result.objects.get(id=record_id)
    video.delete()
    return redirect('growlivapp:scan_detail_page')

growlivapp/templates/growlivapp/Authbarbase.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'growlivapp/login.css' %}">
    <title>Mite Count Pro</title>
</head>
<body>
{% block body_block %}
    ***
{% endblock %}
</body>

growlivapp/templates/growlivapp/authbarbase.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'growlivapp/login.css' %}">
    <title>Mite Count Pro</title>
    
</head>
<body>

{% if user.is_authenticated %}
    <div class="loading-overlay" id="loading-overlay">
        <div class="loading-spinner"></div>
    </div>
    
    <div class="header">
        <div class="logo-container" style="padding-left: 40px">
            <img src="{% static 'growlivapp/final.png' %}" alt="Mite Count Pro" class="logo w-8 h-8">
            <div><a href="{% url 'growlivapp:home' %}" class="font-bold">Mite Count Pro</a></div>
        </div>
        <div class="navigation">
            <a href="{% url 'growlivapp:scan_detail_page' %}">History</a>
            <a href="{% url 'growlivapp:profile' %}">Profile</a>
            <a href="{% url 'growlivapp:logout_user' %}">Logout</a>
        </div>
    </div>
{% endif %}

{% block body_block %}
    ***
{% endblock %}
</body>

growlivapp/templates/growlivapp/base.html
{% load static %}
<html lang="en">
<head>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body {
            background-color: #fff;
            margin: 0;
            padding: 0;
        }

        /* Header Styles */
        .header {
            height: 50px;
            padding-top: 10px;
            padding-bottom: 10px;
            background-color: #fff;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
        }

        .header .logo {
            margin-right: 0.5rem;
        }

        .header a {
            color: #4a5568;
            text-decoration: none;
            margin-right: 1rem;
        }

        .header a:hover {
            color: #1a202c;
        }

        .header .logo-container {
            display: flex;
            align-items: center;
        }

        .header .navigation {
            display: flex;
            align-items: center;
        }

        .home-btn {
            text-align: center;
            cursor: pointer;
            border-radius: 5em;
            color: #fff;
            background: #6dae0b;
            border: 0;
            padding: 10px 40px;
            font-family: 'Ubuntu', sans-serif;
            /*margin-left: 35%;*/
            font-size: 13px;
            box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
        }

        .delete-btn {
            text-align: center;
            cursor: pointer;
            border-radius: 5em;
            color: #fff;
            background: red;
            border: 0;
            padding: 10px 40px;
            font-family: 'Ubuntu', sans-serif;
            font-size: 13px;
            box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
        }
        .logo {
            position: relative;
            width: 40px;
            height: 40px;
        }
        .loading-overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(255, 255, 255, 0.7);
            display: none;
            align-items: center;
            justify-content: center;
            z-index: 9999;
        }

        .loading-overlay.active {
            display: flex;
        }

        .loading-spinner {
            border: 4px solid rgba(0, 0, 0, .1);
            width: 136px;
            height: 136px;
            border-radius: 50%;
            border-left-color: #09f;
            animation: spin 1s infinite linear;
        }

        @keyframes spin {
            0% {
                transform: rotate(0deg);
            }
            100% {
                transform: rotate(360deg);
            }
        }
        .growliv-logo {
            width: 400px;
            height: 400px;
            margin-top: 50px;
            align-self: center;
        }
        .contain {
            display: flex;
            justify-content: center;
            
        }
        
    </style>
</head>
<body>
<div class="header">
    <div class="logo-container" style="padding-left: 50px">
        <img src="{% static 'growlivapp/final.png' %}" alt="Mite Count Pro" class="logo w-8 h-8">
        <div><a href="{% url 'growlivapp:home' %}" class="font-bold">Mite Count Pro</a></div>
    </div>
    <div class="navigation">
        <a href="{% url 'growlivapp:scan_detail_page' %}">History</a>
        <a href="{% url 'growlivapp:profile' %}">Profile</a>
        <a href="{% url 'growlivapp:logout_user' %}">Logout</a>
    </div>
</div>

{% block body_block %}
    ***
{% endblock %}
</body>
</html>

growlivapp/templates/growlivapp/changepassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <style>
        body {
            background-color: #fff; /* white background */
            margin: 0;
            padding: 0;
        }

        .task-bar {
            background-color: inherit; /* inherit background color from body */
            padding: 10px; /* added padding for better spacing */
            display: flex; /* display items in a flex container */
            justify-content: flex-end; /* align items to the right side */
            align-items: center; /* vertically center items */
        }

        .task-bar-text {
            font-family: Arial, Helvetica, sans-serif;
            color: black;
            margin-left: 10px; /* added margin between the texts */
        }

        .container {
            max-width: 600px;
            margin: 50px auto 100px; /* adjusted margin for slightly positioning towards the top */
            text-align: center;
            position: relative; /* added position relative for positioning absolute elements inside */
        }

        .logo {
            position: absolute;
            top: 5; /* position at the top of the task bar */
            left: 10px;
            width: 30px; /* original width of Mite Count Pro logo */
            height: 30px; /* original height of Mite Count Pro logo */
        }

        .mite-count-pro-text {
            position: absolute;
            top: 15px; /* position at the top of the task bar */
            left: 45px; /* adjusted left position to create space between the logos */
            font-size: 16px;
            font-family: Arial, Helvetica, sans-serif;
        }

        .growliv-logo {
            width: 300px; /* set width to 300 pixels */
            height: 300px; /* set height to 300 pixels */
            margin-top: 50px; /* added margin-top to create space between the logos and the form */
        }

        .login-form {
            margin-top: 50px;
        }

        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: none;
            border-radius: 20px; /* curve the edges */
            background-color: #4CAF50;
            color: white;
            cursor: pointer;
        }

        .task-bar {
            background-color: inherit; /* inherit background color from body */
            padding: 15px; /* added padding for better spacing */
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2); /* imaginary lightly colored border */

        }

        .alert {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid transparent;
            border-radius: 4px;
        }

        .alert-success {
            color: #3c763d;
            background-color: #dff0d8;
            border-color: #d6e9c6;
        }

        .alert-error {
            color: #a94442;
            background-color: #f2dede;
            border-color: #ebccd1;
        }

    </style>
</head>
<body>
<div class="container">
    <div class="main">
        <img src="{% static 'growlivapp/logo1.png' %}" alt="Growliv Business Logo" class="growliv-logo">
        {% if err %}
            <p class="error">{{ err }}</p>
        {% endif %}
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
        <form action="{% url 'growlivapp:change_password' %}" method="post">
            {% csrf_token %}
            <input type="password" name="old_password" placeholder="Current password" required>
            <input type="password" name="new_password1" placeholder="New password" required>
            <input type="password" name="new_password2" placeholder="Confirm new password" required>
            <input type="submit" value="Submit">
        </form>

    </div>
</div>



</body>
</html>

growlivapp/templates/growlivapp/home.html
{% extends 'growlivapp/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <style>
        body, html {
            height: 100%; /* Full height */
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #f7fafc; /* Adjust the background color as needed */
        }

        input[type="submit"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: none;
            border-radius: 20px;
            background-color: #4CAF50;
            color: white;
            cursor: pointer;
        }

        
    </style>
</head>
<body>

{% block body_block %}
    <div class="loading-overlay" id="loading-overlay">
        <div class="loading-spinner"></div>
    </div>
    <div class="contain">
        <div class="main">
            <img src="{% static "growlivapp/scan.png" %}" alt="Upload Image" class="growliv-logo" id="upload-image">
            <div class="login-form">
                <form method="post" action="{% url 'growlivapp:upload' %}" enctype="multipart/form-data"
                      id="upload-form">
                    {% csrf_token %}
                    <input id="file-upload" type="file" name="video" style="display:none;"/>
                </form>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.getElementById('upload-image').addEventListener('click', function () {
                document.getElementById('file-upload').click();
            });

            document.getElementById('file-upload').addEventListener('change', function () {
                document.getElementById('loading-overlay').classList.add('active');
                document.getElementById('upload-form').submit();
            });
        });
    </script>
{% endblock %}
</body>
</html>

growlivapp/templates/growlivapp/login.html
{% extends 'growlivapp/authbarbase.html' %}
{% load static %}
{% block body_block %}
    <div class="container">
        <div class="main">
            <img src="{% static 'growlivapp/logo1.png' %}" alt="Growliv Business Logo" class="growliv-logo">
            {% if err %}
                <p class="error">{{ err }}</p>
            {% endif %}
            <form class="form1" action="{% url 'growlivapp:login' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="submit">Sign in</button>
            </form>
            <p>Don't have an account? <a href="{% url 'growlivapp:signup' %}">Sign up</a></p>
            <p class="forgot"><a href="{% url 'growlivapp:forgot_password' %}">Forgot Password?</a></p>
            <p style="padding-bottom: 5%"><a href="../admin/">Admin Login</a></p>
        </div>
    </div>
{% endblock %}

growlivapp/templates/growlivapp/profile.html
{% extends 'growlivapp/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile - Mite Count Pro</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100">
{% block body_block %}
    <main class="p-6 flex-grow">
        <div class="max-w-xl mx-auto">
            <div class="bg-white p-6 shadow rounded">
                <h1 class="text-2xl font-bold text-center mb-6">User Information</h1>
                <form method="post" action="{% url 'growlivapp:profile' %}">
                    {% csrf_token %}
                    <div class="w-full mb-3">
                        <label class="text-gray-700">Email</label>
                        {{ business.email }}
                    </div>
                    <div class="w-full mb-3">
                        <label class="text-gray-700">Business Name</label>
                        {{ business.business_name }}
                    </div>
                    <div class="w-full mb-3">
                        <label class="text-gray-700">Business Contact</label>
                        {{ business.business_phone }}
                    </div>
                    <div class="w-full mb-3">
                        <label class="text-gray-700">Contact Name</label>
                        {{ business.contact_person_name }}
                    </div>
                    <div class="flex flex-col items-center pb-10" style="padding-top: 40px">
                        <div class="w-full mb-3">
                            <button type="submit"
                                    class="w-full text-center block bg-green-600 text-white p-2 rounded hover:bg-green-800">
                                Save Changes
                            </button>
                        </div>
                        <div class="w-full mb-3">
                            <a href="{% url 'growlivapp:change_password' %}"
                               class="w-full text-center block bg-blue-500 text-white p-2 rounded hover:bg-blue-600">Change
                                Password</a>
                        </div>
                        <div class="w-full">
                            <a href="#"
                               class="w-full text-center block bg-red-500 text-white p-2 rounded hover:bg-red-600">Delete
                                Account</a>
                        </div>
                        {% if messages %}
                            <div class="messages">
                                {% for message in messages %}
                                    <div class="alert {{ message.tags }}">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </main>
    <script>
        inputs = document.querySelectorAll('input');
        // Add a classes to each input field
        inputs.forEach(input => {
            input.classList.add('w-full', 'p-2', 'border', 'rounded');
        });
    </script>
{% endblock %}

</body>
</html>